---
name: Compare build
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compare
        run: |
          cd build
          ./build -file ../haproxy-spec.yaml > haproxy_spec_to_compare.yaml
          diff -u haproxy_spec.yaml haproxy_spec_to_compare.yaml
      - name: YAML script validation
        run: |
          chmod +x ./scripts/lint-yaml.sh
          ./scripts/lint-yaml.sh
